### ISSUE TITLE
MySQL Packet SIze Limit

### ISSUE THREAD

**Issue by pmanko** [IsantePlus/openmrs-module-xds-sender#55]
Issue when saving CCD:

```
Caused by: com.mysql.jdbc.PacketTooBigException: Packet for query is too large (7057599 > 4194304). You can change this value on the server by setting the max_allowed_packet' variable.
        at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3915)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2598)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2778)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2825)
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2156)
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2441)
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2366)
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2350)
        at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:147)
        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:208)
        ... 108 more  
 ```

**Comment by pmanko** [comment]
https://forums.aws.amazon.com/thread.jspa?threadID=37852

**Comment by pmanko** [comment]
Closing as stale/outdated during backlog cleanup — inactive for multiple years and no longer planned. Please reopen if still relevant.
